version: '3.8'

volumes:
  postgres_prod_data:
  postgres_dev_data:

services:
  postgres-prod:
    image: postgres:14.7
    container_name: postgres-prod
    ports:
      - '${POSTGRES_PORT_PROD}:5432' # Production DB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: always

  postgres-dev:
    image: postgres:14.7
    container_name: postgres-dev
    ports:
      - '${POSTGRES_PORT_DEV}:5432' # Development DB
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: always
