name: CI/CD for Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Docker Hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/half-time-dev:latest --build-arg NODE_ENV=development .
        docker push ${{ secrets.DOCKER_USERNAME }}/half-time-dev:latest

    # 4. EC2로 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{secrets.EC2_PUBLIC_IP}}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/app

          # docker-compose.yml 최신 상태로 업데이트 (필요 시 Git Pull 또는 SCP로 전송)
          docker-compose down || true
          docker-compose pull
          docker-compose up -d
