name: CI/CD for Develop
on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. .env.develop 파일 생성
    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_DEVELOP }}" > .env.develop

    # 3. Docker Hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Docker 이미지 빌드 및 푸시 (캐시 무효화 적용)
    - name: Build and Push Docker Image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/half-time-dev:latest --build-arg NODE_ENV=development .
        docker push ${{ secrets.DOCKER_USERNAME }}/half-time-dev:latest

    # 5. EC2로 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/app

          # Docker Compose 종료 및 캐시된 Docker 이미지 삭제
          docker-compose down || true
          docker image prune -f

          # 최신 이미지 가져오기 및 서비스 재시작 (최신화 강제 적용)
          docker-compose pull
          docker-compose up --force-recreate --no-deps -d
